//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietPreparation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DietPreparation.Resources.ContentResources", typeof(ContentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Application.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Controls.
        /// </summary>
        public static string AccessControls {
            get {
                return ResourceManager.GetString("AccessControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access level.
        /// </summary>
        public static string AccessTypeLabel {
            get {
                return ResourceManager.GetString("AccessTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Ingredient Concentration.
        /// </summary>
        public static string ActiveIngredientConcentration {
            get {
                return ResourceManager.GetString("ActiveIngredientConcentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add batch size.
        /// </summary>
        public static string AddBatchSize {
            get {
                return ResourceManager.GetString("AddBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Needed.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Requested.
        /// </summary>
        public static string AmountRequested {
            get {
                return ResourceManager.GetString("AmountRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Records.
        /// </summary>
        public static string AuditRecords {
            get {
                return ResourceManager.GetString("AuditRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag Count.
        /// </summary>
        public static string BagCount {
            get {
                return ResourceManager.GetString("BagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag labels.
        /// </summary>
        public static string BagLabels {
            get {
                return ResourceManager.GetString("BagLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag numbers.
        /// </summary>
        public static string BagNumbers {
            get {
                return ResourceManager.GetString("BagNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter bag numbers and/or ranges separated by commas. Ex: 1,3,5-12.
        /// </summary>
        public static string BagNumbersHint {
            get {
                return ResourceManager.GetString("BagNumbersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basal Diet.
        /// </summary>
        public static string BasalDiet {
            get {
                return ResourceManager.GetString("BasalDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basal Diet Code.
        /// </summary>
        public static string BasalDietCode {
            get {
                return ResourceManager.GetString("BasalDietCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basal Diet Name.
        /// </summary>
        public static string BasalDietName {
            get {
                return ResourceManager.GetString("BasalDietName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basal Diets.
        /// </summary>
        public static string BasalDiets {
            get {
                return ResourceManager.GetString("BasalDiets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASAL ID.
        /// </summary>
        public static string BasalIdShort {
            get {
                return ResourceManager.GetString("BasalIdShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Amount.
        /// </summary>
        public static string BatchAmount {
            get {
                return ResourceManager.GetString("BatchAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batches.
        /// </summary>
        public static string Batches {
            get {
                return ResourceManager.GetString("Batches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batches to be mixed.
        /// </summary>
        public static string BatchesToBeMixed {
            get {
                return ResourceManager.GetString("BatchesToBeMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch List.
        /// </summary>
        public static string BatchList {
            get {
                return ResourceManager.GetString("BatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Oum.
        /// </summary>
        public static string BatchOum {
            get {
                return ResourceManager.GetString("BatchOum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch size.
        /// </summary>
        public static string BatchSize {
            get {
                return ResourceManager.GetString("BatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Feedstuff Planning.
        /// </summary>
        public static string BulkFeedstuffPlanning {
            get {
                return ResourceManager.GetString("BulkFeedstuffPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit.
        /// </summary>
        public static string BusinessUnit {
            get {
                return ResourceManager.GetString("BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Operator.
        /// </summary>
        public static string ChangeOperator {
            get {
                return ResourceManager.GetString("ChangeOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Reason.
        /// </summary>
        public static string ChangeReason {
            get {
                return ResourceManager.GetString("ChangeReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Timestamp.
        /// </summary>
        public static string ChangeTimestamp {
            get {
                return ResourceManager.GetString("ChangeTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Type.
        /// </summary>
        public static string ChangeType {
            get {
                return ResourceManager.GetString("ChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Process Work Order.
        /// </summary>
        public static string CloseProcessWorkOrder {
            get {
                return ResourceManager.GetString("CloseProcessWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Work Order.
        /// </summary>
        public static string CloseWorkOrder {
            get {
                return ResourceManager.GetString("CloseWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments Line 1.
        /// </summary>
        public static string CommentsLine1 {
            get {
                return ResourceManager.GetString("CommentsLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments Line 2.
        /// </summary>
        public static string CommentsLine2 {
            get {
                return ResourceManager.GetString("CommentsLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMENTS.
        /// </summary>
        public static string CommentsShort {
            get {
                return ResourceManager.GetString("CommentsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metabolism &amp; Safety.
        /// </summary>
        public static string CompanyDomain {
            get {
                return ResourceManager.GetString("CompanyDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed By.
        /// </summary>
        public static string CompletedBy {
            get {
                return ResourceManager.GetString("CompletedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        public static string Concentration {
            get {
                return ResourceManager.GetString("Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONC.
        /// </summary>
        public static string ConcentrationShort {
            get {
                return ResourceManager.GetString("ConcentrationShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlled Substance.
        /// </summary>
        public static string ControlledSubstance {
            get {
                return ResourceManager.GetString("ControlledSubstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Process Work Order.
        /// </summary>
        public static string CreateProcessWorkOrder {
            get {
                return ResourceManager.GetString("CreateProcessWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Process Work Orders.
        /// </summary>
        public static string CreateProcessWorkOrders {
            get {
                return ResourceManager.GetString("CreateProcessWorkOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Repeat Diet Request.
        /// </summary>
        public static string CreateRepeatDietRequest {
            get {
                return ResourceManager.GetString("CreateRepeatDietRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cust ID.
        /// </summary>
        public static string CustomerIdLabel {
            get {
                return ResourceManager.GetString("CustomerIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Profile.
        /// </summary>
        public static string CustomerProfile {
            get {
                return ResourceManager.GetString("CustomerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string CustomerTypeLabel {
            get {
                return ResourceManager.GetString("CustomerTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Completed.
        /// </summary>
        public static string DateCompleted {
            get {
                return ResourceManager.GetString("DateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date End.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Needed.
        /// </summary>
        public static string DateNeeded {
            get {
                return ResourceManager.GetString("DateNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Request.
        /// </summary>
        public static string DateOfRequest {
            get {
                return ResourceManager.GetString("DateOfRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Start.
        /// </summary>
        public static string DateStart {
            get {
                return ResourceManager.GetString("DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Batches.
        /// </summary>
        public static string DefineBatches {
            get {
                return ResourceManager.GetString("DefineBatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver To.
        /// </summary>
        public static string DeliverTo {
            get {
                return ResourceManager.GetString("DeliverTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Data.
        /// </summary>
        public static string DeliveryData {
            get {
                return ResourceManager.GetString("DeliveryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Location.
        /// </summary>
        public static string DeliveryLocation {
            get {
                return ResourceManager.GetString("DeliveryLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string DeliveryLocationBuilding {
            get {
                return ResourceManager.GetString("DeliveryLocationBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DeliveryLocationDescription {
            get {
                return ResourceManager.GetString("DeliveryLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location ID.
        /// </summary>
        public static string DeliveryLocationID {
            get {
                return ResourceManager.GetString("DeliveryLocationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab.
        /// </summary>
        public static string DeliveryLocationLab {
            get {
                return ResourceManager.GetString("DeliveryLocationLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Locations.
        /// </summary>
        public static string DeliveryLocations {
            get {
                return ResourceManager.GetString("DeliveryLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit.
        /// </summary>
        public static string DeliveryLocationUnit {
            get {
                return ResourceManager.GetString("DeliveryLocationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Notice.
        /// </summary>
        public static string DeliveryNotice {
            get {
                return ResourceManager.GetString("DeliveryNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Work Order.
        /// </summary>
        public static string DetailPWOTitle {
            get {
                return ResourceManager.GetString("DetailPWOTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Data.
        /// </summary>
        public static string DietData {
            get {
                return ResourceManager.GetString("DietData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Drug.
        /// </summary>
        public static string DietDrug {
            get {
                return ResourceManager.GetString("DietDrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Ingredients.
        /// </summary>
        public static string DietIngredients {
            get {
                return ResourceManager.GetString("DietIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Name.
        /// </summary>
        public static string DietName {
            get {
                return ResourceManager.GetString("DietName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Preparation.
        /// </summary>
        public static string DietPreparation {
            get {
                return ResourceManager.GetString("DietPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Request.
        /// </summary>
        public static string DietRequest {
            get {
                return ResourceManager.GetString("DietRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Requests.
        /// </summary>
        public static string DietRequests {
            get {
                return ResourceManager.GetString("DietRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Request Search.
        /// </summary>
        public static string DietRequestSearch {
            get {
                return ResourceManager.GetString("DietRequestSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Repeat Request.
        /// </summary>
        public static string DietRequestToBeDisabled {
            get {
                return ResourceManager.GetString("DietRequestToBeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Repeat Request.
        /// </summary>
        public static string DietRequestToBeEnabled {
            get {
                return ResourceManager.GetString("DietRequestToBeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Print Labels.
        /// </summary>
        public static string DoNotPrintLabels {
            get {
                return ResourceManager.GetString("DoNotPrintLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug.
        /// </summary>
        public static string Drug {
            get {
                return ResourceManager.GetString("Drug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        public static string DrugConcentration {
            get {
                return ResourceManager.GetString("DrugConcentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Label.
        /// </summary>
        public static string DrugLabelPage {
            get {
                return ResourceManager.GetString("DrugLabelPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Library.
        /// </summary>
        public static string DrugLibrary {
            get {
                return ResourceManager.GetString("DrugLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mfg Lot #.
        /// </summary>
        public static string DrugMfgLotNumber {
            get {
                return ResourceManager.GetString("DrugMfgLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Name.
        /// </summary>
        public static string DrugName {
            get {
                return ResourceManager.GetString("DrugName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs.
        /// </summary>
        public static string Drugs {
            get {
                return ResourceManager.GetString("Drugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRUG.
        /// </summary>
        public static string DrugShort {
            get {
                return ResourceManager.GetString("DrugShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be in the format.
        /// </summary>
        public static string EmailMustBeFormat {
            get {
                return ResourceManager.GetString("EmailMustBeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPIRE DATE.
        /// </summary>
        public static string ExpirationDateShort {
            get {
                return ResourceManager.GetString("ExpirationDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPIRES.
        /// </summary>
        public static string ExpiresDateShort {
            get {
                return ResourceManager.GetString("ExpiresDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string Feed {
            get {
                return ResourceManager.GetString("Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Additive.
        /// </summary>
        public static string FeedAdditive {
            get {
                return ResourceManager.GetString("FeedAdditive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Labels.
        /// </summary>
        public static string FeedLabels {
            get {
                return ResourceManager.GetString("FeedLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedstuff.
        /// </summary>
        public static string Feedstuff {
            get {
                return ResourceManager.GetString("Feedstuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Supplier.
        /// </summary>
        public static string FeedSupplier {
            get {
                return ResourceManager.GetString("FeedSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Type.
        /// </summary>
        public static string FeedType {
            get {
                return ResourceManager.GetString("FeedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering Year.
        /// </summary>
        public static string FilteringYear {
            get {
                return ResourceManager.GetString("FilteringYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not display Diet Requests, Process Work Orders or Feed Labels created prior to the year.
        /// </summary>
        public static string FilteringYearMessage {
            get {
                return ResourceManager.GetString("FilteringYearMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for diet.
        /// </summary>
        public static string ForDiet {
            get {
                return ResourceManager.GetString("ForDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Comments.
        /// </summary>
        public static string GeneralComments {
            get {
                return ResourceManager.GetString("GeneralComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Home.
        /// </summary>
        public static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard Code.
        /// </summary>
        public static string HazardCode {
            get {
                return ResourceManager.GetString("HazardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included in Weight.
        /// </summary>
        public static string IncludedInWeight {
            get {
                return ResourceManager.GetString("IncludedInWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.
        /// </summary>
        public static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Weight.
        /// </summary>
        public static string IngredientWeight {
            get {
                return ResourceManager.GetString("IngredientWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial.
        /// </summary>
        public static string Initial {
            get {
                return ResourceManager.GetString("Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intended Use.
        /// </summary>
        public static string IntendedUse {
            get {
                return ResourceManager.GetString("IntendedUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab.
        /// </summary>
        public static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        public static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        public static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot ID.
        /// </summary>
        public static string LotId {
            get {
                return ResourceManager.GetString("LotId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Number.
        /// </summary>
        public static string LotNumber {
            get {
                return ResourceManager.GetString("LotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOT NO.
        /// </summary>
        public static string LotNumberShort {
            get {
                return ResourceManager.GetString("LotNumberShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Year.
        /// </summary>
        public static string LotYear {
            get {
                return ResourceManager.GetString("LotYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactured Date.
        /// </summary>
        public static string ManufacturedDate {
            get {
                return ResourceManager.GetString("ManufacturedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Lot #.
        /// </summary>
        public static string ManufacturerLot {
            get {
                return ResourceManager.GetString("ManufacturerLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicated Pre-Mix.
        /// </summary>
        public static string MedicatedPreMix {
            get {
                return ResourceManager.GetString("MedicatedPreMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer Used.
        /// </summary>
        public static string Mixer {
            get {
                return ResourceManager.GetString("Mixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixing Instructions.
        /// </summary>
        public static string MixingInstructions {
            get {
                return ResourceManager.GetString("MixingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Diet.
        /// </summary>
        public static string NewDiet {
            get {
                return ResourceManager.GetString("NewDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Drug.
        /// </summary>
        public static string NewDrug {
            get {
                return ResourceManager.GetString("NewDrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-production error.
        /// </summary>
        public static string NonProductionError {
            get {
                return ResourceManager.GetString("NonProductionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of batches.
        /// </summary>
        public static string NumberOfBatches {
            get {
                return ResourceManager.GetString("NumberOfBatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of copies.
        /// </summary>
        public static string NumberOfCopies {
            get {
                return ResourceManager.GetString("NumberOfCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only closed process work orders are displayed by this report..
        /// </summary>
        public static string OnlyClosedProcessWorkOrders {
            get {
                return ResourceManager.GetString("OnlyClosedProcessWorkOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops .
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging Instructions.
        /// </summary>
        public static string PackagingInstructions {
            get {
                return ResourceManager.GetString("PackagingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcking Instructions.
        /// </summary>
        public static string ParckingInstructions {
            get {
                return ResourceManager.GetString("ParckingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent of Total Diet.
        /// </summary>
        public static string PercentOfTotalDiet {
            get {
                return ResourceManager.GetString("PercentOfTotalDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premix.
        /// </summary>
        public static string Premix {
            get {
                return ResourceManager.GetString("Premix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Mix to be used.
        /// </summary>
        public static string PreMixName {
            get {
                return ResourceManager.GetString("PreMixName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Mix to be Activated.
        /// </summary>
        public static string PremixToBeActivated {
            get {
                return ResourceManager.GetString("PremixToBeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Mix to be De-Activated.
        /// </summary>
        public static string PremixToBeDeactivated {
            get {
                return ResourceManager.GetString("PremixToBeDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Bag Numbers.
        /// </summary>
        public static string PrintBagNumbers {
            get {
                return ResourceManager.GetString("PrintBagNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        public static string Printing {
            get {
                return ResourceManager.GetString("Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Instructions.
        /// </summary>
        public static string ProcessingInstructions {
            get {
                return ResourceManager.GetString("ProcessingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Work Order.
        /// </summary>
        public static string ProcessWorkOrder {
            get {
                return ResourceManager.GetString("ProcessWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Work Orders.
        /// </summary>
        public static string ProcessWorkOrders {
            get {
                return ResourceManager.GetString("ProcessWorkOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Preparation system.
        /// </summary>
        public static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project #.
        /// </summary>
        public static string ProjectID {
            get {
                return ResourceManager.GetString("ProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT.
        /// </summary>
        public static string ProjectShort {
            get {
                return ResourceManager.GetString("ProjectShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pwo Id.
        /// </summary>
        public static string PwoId {
            get {
                return ResourceManager.GetString("PwoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected batch size(s)..
        /// </summary>
        public static string RemoveSelectedBatchSize {
            get {
                return ResourceManager.GetString("RemoveSelectedBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat 2006 Requests.
        /// </summary>
        public static string Repeat2006Requests {
            get {
                return ResourceManager.GetString("Repeat2006Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Requests.
        /// </summary>
        public static string RepeatRequests {
            get {
                return ResourceManager.GetString("RepeatRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprint.
        /// </summary>
        public static string Reprint {
            get {
                return ResourceManager.GetString("Reprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprinting.
        /// </summary>
        public static string Reprinting {
            get {
                return ResourceManager.GetString("Reprinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested By.
        /// </summary>
        public static string RequestedBy {
            get {
                return ResourceManager.GetString("RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor.
        /// </summary>
        public static string Requestor {
            get {
                return ResourceManager.GetString("Requestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to.
        /// </summary>
        public static string ReturnTo {
            get {
                return ResourceManager.GetString("ReturnTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Type.
        /// </summary>
        public static string SampleAnalysisType {
            get {
                return ResourceManager.GetString("SampleAnalysisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string SampleComments {
            get {
                return ResourceManager.GetString("SampleComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition.
        /// </summary>
        public static string SampleDisposition {
            get {
                return ResourceManager.GetString("SampleDisposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search 2006 Work Orders.
        /// </summary>
        public static string Search2006WorkOrders {
            get {
                return ResourceManager.GetString("Search2006WorkOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one.
        /// </summary>
        public static string SectionOne {
            get {
                return ResourceManager.GetString("SectionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Audit Record.
        /// </summary>
        public static string SelectAuditRecord {
            get {
                return ResourceManager.GetString("SelectAuditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence #.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Number.
        /// </summary>
        public static string SequenceNumber {
            get {
                return ResourceManager.GetString("SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-Cuts.
        /// </summary>
        public static string ShortCuts {
            get {
                return ResourceManager.GetString("ShortCuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Number.
        /// </summary>
        public static string StudyNumber {
            get {
                return ResourceManager.GetString("StudyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STUDY.
        /// </summary>
        public static string StudyShort {
            get {
                return ResourceManager.GetString("StudyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Type.
        /// </summary>
        public static string StudyType {
            get {
                return ResourceManager.GetString("StudyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Completed.
        /// </summary>
        public static string TimeCompleted {
            get {
                return ResourceManager.GetString("TimeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to print.
        /// </summary>
        public static string ToPrint {
            get {
                return ResourceManager.GetString("ToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to reprint.
        /// </summary>
        public static string ToReprint {
            get {
                return ResourceManager.GetString("ToReprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total for batch size.
        /// </summary>
        public static string TotalForBatchSize {
            get {
                return ResourceManager.GetString("TotalForBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Ingredients.
        /// </summary>
        public static string TotalIngredients {
            get {
                return ResourceManager.GetString("TotalIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Request Amount.
        /// </summary>
        public static string TotalRequestAmount {
            get {
                return ResourceManager.GetString("TotalRequestAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic Hazard.
        /// </summary>
        public static string ToxicHazard {
            get {
                return ResourceManager.GetString("ToxicHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure.
        /// </summary>
        public static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unscheduled.
        /// </summary>
        public static string Unscheduled {
            get {
                return ResourceManager.GetString("Unscheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network user id.
        /// </summary>
        public static string UserIdLabel {
            get {
                return ResourceManager.GetString("UserIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Audit Log.
        /// </summary>
        public static string ViewAuditLog {
            get {
                return ResourceManager.GetString("ViewAuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Diet Preparation System.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Orders.
        /// </summary>
        public static string WorkOrders {
            get {
                return ResourceManager.GetString("WorkOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zpl.
        /// </summary>
        public static string Zpl {
            get {
                return ResourceManager.GetString("Zpl", resourceCulture);
            }
        }
    }
}
