//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietPreparation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DietPreparation.Resources.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string AccessType_Admin {
            get {
                return ResourceManager.GetString("AccessType_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string AccessType_Disabled {
            get {
                return ResourceManager.GetString("AccessType_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Only.
        /// </summary>
        public static string AccessType_OrderOnly {
            get {
                return ResourceManager.GetString("AccessType_OrderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string AccessType_User {
            get {
                return ResourceManager.GetString("AccessType_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antibiotic Screen.
        /// </summary>
        public static string AnalysisType_AntibioticScreen {
            get {
                return ResourceManager.GetString("AnalysisType_AntibioticScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrient Analysis.
        /// </summary>
        public static string AnalysisType_NutrientAnalysis {
            get {
                return ResourceManager.GetString("AnalysisType_NutrientAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string AnalysisType_Other {
            get {
                return ResourceManager.GetString("AnalysisType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retainer Sample.
        /// </summary>
        public static string AnalysisType_RetainerSample {
            get {
                return ResourceManager.GetString("AnalysisType_RetainerSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basal.
        /// </summary>
        public static string BaseFeedType_Basal {
            get {
                return ResourceManager.GetString("BaseFeedType_Basal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External\Internal Feed.
        /// </summary>
        public static string BaseFeedType_ExternalInternalFeed {
            get {
                return ResourceManager.GetString("BaseFeedType_ExternalInternalFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g/ton.
        /// </summary>
        public static string ConcentrationUnitOfMeasure_GramOnTon {
            get {
                return ResourceManager.GetString("ConcentrationUnitOfMeasure_GramOnTon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg/kg.
        /// </summary>
        public static string ConcentrationUnitOfMeasure_MilligramOnKilogram {
            get {
                return ResourceManager.GetString("ConcentrationUnitOfMeasure_MilligramOnKilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg/lb.
        /// </summary>
        public static string ConcentrationUnitOfMeasure_MilligramOnPounds {
            get {
                return ResourceManager.GetString("ConcentrationUnitOfMeasure_MilligramOnPounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOTH.
        /// </summary>
        public static string CustomerType_Both {
            get {
                return ResourceManager.GetString("CustomerType_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVER TO.
        /// </summary>
        public static string CustomerType_Receiver {
            get {
                return ResourceManager.GetString("CustomerType_Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUESTER.
        /// </summary>
        public static string CustomerType_Requester {
            get {
                return ResourceManager.GetString("CustomerType_Requester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basal.
        /// </summary>
        public static string FeedType_Basal {
            get {
                return ResourceManager.GetString("FeedType_Basal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string FeedType_External {
            get {
                return ResourceManager.GetString("FeedType_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string FeedType_Internal {
            get {
                return ResourceManager.GetString("FeedType_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crumbles.
        /// </summary>
        public static string Form_Crumbles {
            get {
                return ResourceManager.GetString("Form_Crumbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid.
        /// </summary>
        public static string Form_Liquid {
            get {
                return ResourceManager.GetString("Form_Liquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal.
        /// </summary>
        public static string Form_Meal {
            get {
                return ResourceManager.GetString("Form_Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pellet.
        /// </summary>
        public static string Form_Pellet {
            get {
                return ResourceManager.GetString("Form_Pellet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known.
        /// </summary>
        public static string HazardType_Known {
            get {
                return ResourceManager.GetString("HazardType_Known", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Hazardous.
        /// </summary>
        public static string HazardType_Nonhazardous {
            get {
                return ResourceManager.GetString("HazardType_Nonhazardous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string HazardType_Unknown {
            get {
                return ResourceManager.GetString("HazardType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string IntendedUse_External {
            get {
                return ResourceManager.GetString("IntendedUse_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string IntendedUse_Internal {
            get {
                return ResourceManager.GetString("IntendedUse_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string PwoConfirmType_Label {
            get {
                return ResourceManager.GetString("PwoConfirmType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWO.
        /// </summary>
        public static string PwoConfirmType_Pwo {
            get {
                return ResourceManager.GetString("PwoConfirmType_Pwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Diet.
        /// </summary>
        public static string RequestType_CompleteDiet {
            get {
                return ResourceManager.GetString("RequestType_CompleteDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicated Pre-Mix.
        /// </summary>
        public static string RequestType_MedicatedPremix {
            get {
                return ResourceManager.GetString("RequestType_MedicatedPremix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplemental Diet.
        /// </summary>
        public static string RequestType_SupplementalDiet {
            get {
                return ResourceManager.GetString("RequestType_SupplementalDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCP.
        /// </summary>
        public static string StudyType_Gcp {
            get {
                return ResourceManager.GetString("StudyType_Gcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLP.
        /// </summary>
        public static string StudyType_Glp {
            get {
                return ResourceManager.GetString("StudyType_Glp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-GxP.
        /// </summary>
        public static string StudyType_NonGxp {
            get {
                return ResourceManager.GetString("StudyType_NonGxp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string UnitOfMeasure_Gram {
            get {
                return ResourceManager.GetString("UnitOfMeasure_Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        public static string UnitOfMeasure_Kilogram {
            get {
                return ResourceManager.GetString("UnitOfMeasure_Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        public static string UnitOfMeasure_Milligram {
            get {
                return ResourceManager.GetString("UnitOfMeasure_Milligram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbs.
        /// </summary>
        public static string UnitOfMeasure_Pound {
            get {
                return ResourceManager.GetString("UnitOfMeasure_Pound", resourceCulture);
            }
        }
    }
}
