//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietPreparation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodesDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodesDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DietPreparation.Resources.ErrorCodesDescription", typeof(ErrorCodesDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred. Please try again later..
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested sorting criteria is not implemented. Please use a supported sorting field and try again..
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should be unique.
        /// </summary>
        public static string _10001 {
            get {
                return ResourceManager.GetString("10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should be unique.
        /// </summary>
        public static string _10002 {
            get {
                return ResourceManager.GetString("10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory field is empty. Please, provide any value..
        /// </summary>
        public static string _1001 {
            get {
                return ResourceManager.GetString("1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided value is either too short or too long. Please check the requirements and try again..
        /// </summary>
        public static string _1002 {
            get {
                return ResourceManager.GetString("1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided email is not valid. Please enter a valid email address..
        /// </summary>
        public static string _1003 {
            get {
                return ResourceManager.GetString("1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided email is not valid. It must have a specific domain. Please enter a valid email address..
        /// </summary>
        public static string _1004 {
            get {
                return ResourceManager.GetString("1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided value must be non-negative. Please enter a positive value or zero..
        /// </summary>
        public static string _1005 {
            get {
                return ResourceManager.GetString("1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided sorting criteria is incorrect. Please use a valid sorting field and try again..
        /// </summary>
        public static string _1006 {
            get {
                return ResourceManager.GetString("1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided slope value is incorrect. Please review the value and try again..
        /// </summary>
        public static string _1007 {
            get {
                return ResourceManager.GetString("1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided value is not valid. Please enter a valid value..
        /// </summary>
        public static string _1008 {
            get {
                return ResourceManager.GetString("1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount must be greater than the sum of the included weights of drugs and premixes..
        /// </summary>
        public static string _1009 {
            get {
                return ResourceManager.GetString("1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount must be greater than the sum of the sample amounts..
        /// </summary>
        public static string _1010 {
            get {
                return ResourceManager.GetString("1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drug must be active to be used in the diet request..
        /// </summary>
        public static string _1011 {
            get {
                return ResourceManager.GetString("1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The premix must be active to be used in the diet request..
        /// </summary>
        public static string _1012 {
            get {
                return ResourceManager.GetString("1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided value doesn&apos;t meet a specified format. Please enter a valid value..
        /// </summary>
        public static string _1013 {
            get {
                return ResourceManager.GetString("1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value is too long. Please, decrease value length..
        /// </summary>
        public static string _1014 {
            get {
                return ResourceManager.GetString("1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value is too small. Please, increase value length..
        /// </summary>
        public static string _1015 {
            get {
                return ResourceManager.GetString("1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value is outside permitted period. Please, provide value inside the period..
        /// </summary>
        public static string _1016 {
            get {
                return ResourceManager.GetString("1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value is not in range. Please, provide value in range..
        /// </summary>
        public static string _1017 {
            get {
                return ResourceManager.GetString("1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while connecting to the database. Please try again later..
        /// </summary>
        public static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already existing location with the same address.
        /// </summary>
        public static string _11001 {
            get {
                return ResourceManager.GetString("11001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required parameter is missing. Please check the URL and try again..
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ViewModel is null. Please ensure proper data is provided and try again..
        /// </summary>
        public static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested page or resource could not be found..
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the data. Please try again later..
        /// </summary>
        public static string _2001 {
            get {
                return ResourceManager.GetString("2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the item. Please check your input and try again..
        /// </summary>
        public static string _2002 {
            get {
                return ResourceManager.GetString("2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the item. Please check your input and try again..
        /// </summary>
        public static string _2003 {
            get {
                return ResourceManager.GetString("2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested user could not be found. Please check the user details and try again..
        /// </summary>
        public static string _2004 {
            get {
                return ResourceManager.GetString("2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified UserId already exists. Please choose a different UserId..
        /// </summary>
        public static string _2005 {
            get {
                return ResourceManager.GetString("2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested entity not found..
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the data. Please try again later..
        /// </summary>
        public static string _3001 {
            get {
                return ResourceManager.GetString("3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the item. Please check your input and try again..
        /// </summary>
        public static string _3002 {
            get {
                return ResourceManager.GetString("3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the item. Please check your input and try again..
        /// </summary>
        public static string _3003 {
            get {
                return ResourceManager.GetString("3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requester could not be found. Please check the user details and try again..
        /// </summary>
        public static string _3004 {
            get {
                return ResourceManager.GetString("3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receiver could not be found. Please check the user details and try again..
        /// </summary>
        public static string _3005 {
            get {
                return ResourceManager.GetString("3005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified location could not be found. Please check the address and try again..
        /// </summary>
        public static string _3006 {
            get {
                return ResourceManager.GetString("3006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested basal diet could not be found. Please check the diet and try again..
        /// </summary>
        public static string _3007 {
            get {
                return ResourceManager.GetString("3007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested drug could not be found. Please check the drug and try again..
        /// </summary>
        public static string _3008 {
            get {
                return ResourceManager.GetString("3008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested premix could not be found. Please check the premix and try again..
        /// </summary>
        public static string _3009 {
            get {
                return ResourceManager.GetString("3009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested diet request could not be found. Please update page and try again..
        /// </summary>
        public static string _3010 {
            get {
                return ResourceManager.GetString("3010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while cloning Diet Request. Please try again later..
        /// </summary>
        public static string _3011 {
            get {
                return ResourceManager.GetString("3011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting Diet Request. Please try again later..
        /// </summary>
        public static string _3012 {
            get {
                return ResourceManager.GetString("3012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update of deleted Diet Request is forbidden..
        /// </summary>
        public static string _3013 {
            get {
                return ResourceManager.GetString("3013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update of locked Diet Request is forbidden..
        /// </summary>
        public static string _3014 {
            get {
                return ResourceManager.GetString("3014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while activating Diet Request. Please try again later..
        /// </summary>
        public static string _3015 {
            get {
                return ResourceManager.GetString("3015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was modified by another user. Please refresh and try again..
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the data. Please try again later..
        /// </summary>
        public static string _4001 {
            get {
                return ResourceManager.GetString("4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the item. Please check your input and try again..
        /// </summary>
        public static string _4002 {
            get {
                return ResourceManager.GetString("4002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the item. Please check your input and try again..
        /// </summary>
        public static string _4003 {
            get {
                return ResourceManager.GetString("4003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided name is a duplicate and not allowed. Please enter a unique value..
        /// </summary>
        public static string _4004 {
            get {
                return ResourceManager.GetString("4004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this action..
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the data. Please try again later..
        /// </summary>
        public static string _5001 {
            get {
                return ResourceManager.GetString("5001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while printing the data. Please try again later..
        /// </summary>
        public static string _5002 {
            get {
                return ResourceManager.GetString("5002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while writing to the print file. Please try again later..
        /// </summary>
        public static string _5003 {
            get {
                return ResourceManager.GetString("5003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient permissions to access the print directory or print file..
        /// </summary>
        public static string _5004 {
            get {
                return ResourceManager.GetString("5004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bag numbers format. Please check and retry..
        /// </summary>
        public static string _5005 {
            get {
                return ResourceManager.GetString("5005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this resource..
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the data. Please try again later..
        /// </summary>
        public static string _6001 {
            get {
                return ResourceManager.GetString("6001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the data. Please try again later..
        /// </summary>
        public static string _6002 {
            get {
                return ResourceManager.GetString("6002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided data is invalid or incomplete. Please check your input and try again..
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the data. Please try again later..
        /// </summary>
        public static string _7001 {
            get {
                return ResourceManager.GetString("7001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the data. Please try again later..
        /// </summary>
        public static string _7002 {
            get {
                return ResourceManager.GetString("7002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required value is missing. Please fill in all required fields and try again..
        /// </summary>
        public static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the data. Please try again later..
        /// </summary>
        public static string _8001 {
            get {
                return ResourceManager.GetString("8001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet implemented..
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the data. Please try again later..
        /// </summary>
        public static string _9001 {
            get {
                return ResourceManager.GetString("9001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the item. Please check your input and try again..
        /// </summary>
        public static string _9002 {
            get {
                return ResourceManager.GetString("9002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the item. Please check your input and try again..
        /// </summary>
        public static string _9003 {
            get {
                return ResourceManager.GetString("9003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested customer could not be found. Please check the user details and try again..
        /// </summary>
        public static string _9004 {
            get {
                return ResourceManager.GetString("9004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified CustomerId already exists. Please choose a different CustomerId..
        /// </summary>
        public static string _9005 {
            get {
                return ResourceManager.GetString("9005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Customer Email already exists. Please choose a different Customer Email..
        /// </summary>
        public static string _9006 {
            get {
                return ResourceManager.GetString("9006", resourceCulture);
            }
        }
    }
}
