//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietPreparation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DietPreparation.Resources.MessagesResources", typeof(MessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basal Diet was created successfully..
        /// </summary>
        public static string BasalDietCreated {
            get {
                return ResourceManager.GetString("BasalDietCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basal Diet was updated successfully..
        /// </summary>
        public static string BasalDietUpdated {
            get {
                return ResourceManager.GetString("BasalDietUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch was closed successfully..
        /// </summary>
        public static string BatchClosed {
            get {
                return ResourceManager.GetString("BatchClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batches were created successfully..
        /// </summary>
        public static string BatchWasCreated {
            get {
                return ResourceManager.GetString("BatchWasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this diet request?.
        /// </summary>
        public static string ConfirmDietRequestDeletion {
            get {
                return ResourceManager.GetString("ConfirmDietRequestDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer was created successfully..
        /// </summary>
        public static string CustomerCreated {
            get {
                return ResourceManager.GetString("CustomerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer was updated successfully..
        /// </summary>
        public static string CustomerUpdated {
            get {
                return ResourceManager.GetString("CustomerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Location was created successfully..
        /// </summary>
        public static string DeliveryLocationCreated {
            get {
                return ResourceManager.GetString("DeliveryLocationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Location was updated successfully..
        /// </summary>
        public static string DeliveryLocationUpdated {
            get {
                return ResourceManager.GetString("DeliveryLocationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet request was created successfully..
        /// </summary>
        public static string DietRequestCreated {
            get {
                return ResourceManager.GetString("DietRequestCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet request was deleted successfully..
        /// </summary>
        public static string DietRequestDeleted {
            get {
                return ResourceManager.GetString("DietRequestDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet request was updated successfully..
        /// </summary>
        public static string DietRequestUpdated {
            get {
                return ResourceManager.GetString("DietRequestUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug was created successfully..
        /// </summary>
        public static string DrugCreated {
            get {
                return ResourceManager.GetString("DrugCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug was updated successfully..
        /// </summary>
        public static string DrugUpdated {
            get {
                return ResourceManager.GetString("DrugUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found. Please, create new entity instance or change search params..
        /// </summary>
        public static string EmptyEntityInstancesList {
            get {
                return ResourceManager.GetString("EmptyEntityInstancesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t select anything to perform the operation.
        /// </summary>
        public static string EntityInstancesNotSelected {
            get {
                return ResourceManager.GetString("EntityInstancesNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed label additive download has started..
        /// </summary>
        public static string FeedLabelAdditiveDownloadStarted {
            get {
                return ResourceManager.GetString("FeedLabelAdditiveDownloadStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed label additive sent to print queue..
        /// </summary>
        public static string FeedLabelAdditiveSentPrinter {
            get {
                return ResourceManager.GetString("FeedLabelAdditiveSentPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed label download has started..
        /// </summary>
        public static string FeedLabelDownloadStarted {
            get {
                return ResourceManager.GetString("FeedLabelDownloadStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed label sent to print queue..
        /// </summary>
        public static string FeedLabelSentPrinter {
            get {
                return ResourceManager.GetString("FeedLabelSentPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Year was updated successfully..
        /// </summary>
        public static string FilterYearUpdated {
            get {
                return ResourceManager.GetString("FilterYearUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient was created successfully..
        /// </summary>
        public static string IngredientCreated {
            get {
                return ResourceManager.GetString("IngredientCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient was updated successfully..
        /// </summary>
        public static string IngredientUpdated {
            get {
                return ResourceManager.GetString("IngredientUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location was created successfully..
        /// </summary>
        public static string LocationCreated {
            get {
                return ResourceManager.GetString("LocationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location was updated successfully..
        /// </summary>
        public static string LocationUpdated {
            get {
                return ResourceManager.GetString("LocationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers not configured..
        /// </summary>
        public static string NotFoundPrinters {
            get {
                return ResourceManager.GetString("NotFoundPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format! Use numbers or ranges separated by commas. Ex: 1,3,5-12.
        /// </summary>
        public static string ParseBagNumbersError {
            get {
                return ResourceManager.GetString("ParseBagNumbersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the reason for the change.\nThis entry is required if you wish to proceed..
        /// </summary>
        public static string PleaseEnterReasonForChange {
            get {
                return ResourceManager.GetString("PleaseEnterReasonForChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the reason for the cancellation.\nThis entry is required if you wish to proceed..
        /// </summary>
        public static string PleaseEnterReasonForDelete {
            get {
                return ResourceManager.GetString("PleaseEnterReasonForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Work Orders were created successfully..
        /// </summary>
        public static string ProcessWorkOrdersCreated {
            get {
                return ResourceManager.GetString("ProcessWorkOrdersCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CANCEL If PWO Did Not Print Properly.
        /// </summary>
        public static string PwoDidNotPrintProperly {
            get {
                return ResourceManager.GetString("PwoDidNotPrintProperly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select OK If PWO Printed Properly.
        /// </summary>
        public static string PwoPrintedProperly {
            get {
                return ResourceManager.GetString("PwoPrintedProperly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was created successfully..
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was updated successfully..
        /// </summary>
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DID THE PROCESS WORK ORDER PRINT PROPERLY?.
        /// </summary>
        public static string WorkOrderPrintQuestion {
            get {
                return ResourceManager.GetString("WorkOrderPrintQuestion", resourceCulture);
            }
        }
    }
}
