SELECT DP_LOCATION.LOCATION_ID,
       DP_LOCATION.DELIVER_DESCRIPTION,
       DP_LOCATION.DELIVER_BUILDING,
       DP_LOCATION.DELIVER_FLOOR,
       DP_LOCATION.DELIVER_LAB,
       DP_LOCATION.BUSINESS_UNIT_NUMBER,
       DP_LOCATION.LOCK
FROM DP_LOCATION
WHERE 1=1
@filter