WITH CTE AS (
	SELECT DISTINCT
			DP_REQUEST.REQUEST_ID,
			(CONVERT(varchar,DP_REQUEST.LOT_YEAR) + '-' + CONVERT(varchar,DP_REQUEST.LOT_ID)) AS LOT,
			DP_REQUEST.LOT_YEAR,
			DP_REQUEST.LOT_ID,
			DP_CUSTOMER.FIRST_NAME + ' ' + DP_CUSTOMER.LAST_NAME as REQUESTOR,
			DP_CUSTOMER.LAST_NAME,
			DP_CUSTOMER.FIRST_NAME,
			DP_REQUEST.DATE_REQUEST,
			DP_REQUEST.DIET_NAME,
			DP_REQUEST.REQUEST_AMOUNT,
			DP_REQUEST.REQUEST_UOM,
			COUNT(*) OVER () AS TotalItems
		FROM 
			DP_REQUEST 
				LEFT JOIN DP_CUSTOMER
				ON DP_REQUEST.REQUESTOR_ID = DP_CUSTOMER.CUSTOMER_ID
		WHERE 
			DP_REQUEST.FEED_TYPE NOT LIKE 'External'
			AND DP_REQUEST.LOT_YEAR >= (SELECT TOP 1 Value FROM DP_APP_SETUP)
			@searchText
		@filter
	)
	SELECT 
		REQUEST_ID,
		LOT,
		LOT_YEAR,
		LOT_ID,
		REQUESTOR,
		LAST_NAME,
		FIRST_NAME,
		DATE_REQUEST,
		DIET_NAME,
		REQUEST_AMOUNT,
		REQUEST_UOM,
		TotalItems
	FROM CTE
	@orderBy
	OFFSET (@page - 1) * @pageSize ROWS
	FETCH NEXT @pageSize ROWS ONLY;